// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpotyf4nVnPgrs6oho891TE01B1e9IMaU',
    appId: '1:674251738277:web:de887b58ce7b908723514c',
    messagingSenderId: '674251738277',
    projectId: 'your-matter',
    authDomain: 'your-matter.firebaseapp.com',
    storageBucket: 'your-matter.appspot.com',
    measurementId: 'G-9HMDHJG8P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0i8GdmoH07N9Y7HJJjR4HIb2sHH6Sc4',
    appId: '1:674251738277:android:b27b87794874a5d523514c',
    messagingSenderId: '674251738277',
    projectId: 'your-matter',
    storageBucket: 'your-matter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemqZaSEEsE4SzBNk9AO8YDUmUYRv8fno',
    appId: '1:674251738277:ios:b140c0944f46c37d23514c',
    messagingSenderId: '674251738277',
    projectId: 'your-matter',
    storageBucket: 'your-matter.appspot.com',
    iosBundleId: 'com.yourmatter.app',
  );
}
